---
config: imdb_genre
tab_cols:
  - Year
  - Runtime (Minutes)
  - Rating
  - Votes
  - Revenue (Millions)
  - Metascore
  - Rank
categorical_cols: []
text_cols:
  - Description
label_names:
  - "False"
  - "True"
label_col: Genre_is_Drama
num_labels: 2
prob_type: single_label_classification
wandb_proj_name: IMDB Genre
tnt_reorder_cols:
  bert:
    - Description
    - Rank
    - Votes
    - Revenue (Millions)
    - Metascore
    - Runtime (Minutes)
    - Rating
    - Year
  disbert:
    - Description
    - Votes
    - Rank
    - Revenue (Millions)
    - Runtime (Minutes)
    - Year
    - Metascore
    - Rating
  drob:
    - Description
    - Year
    - Rank
    - Revenue (Millions)
    - Votes
    - Metascore
    - Runtime (Minutes)
    - Rating
  deberta:
    - Description
    - Rank
    - Revenue (Millions)
    - Votes
    - Runtime (Minutes)
    - Metascore
    - Rating
    - Year
base_reorder_cols:
  bert:
    - Description
    - Metascore
    - Revenue (Millions)
    - Rank
    - Rating
    - Votes
    - Runtime (Minutes)
    - Year
  disbert:
    - Description
    - Metascore
    - Rank
    - Rating
    - Revenue (Millions)
    - Votes
    - Year
    - Runtime (Minutes)
  drob:
    - Description
    - Revenue (Millions)
    - Metascore
    - Votes
    - Year
    - Rank
    - Runtime (Minutes)
    - Rating
  deberta:
    - Description
    - Rating
    - Metascore
    - Rank
    - Revenue (Millions)
    - Year
    - Votes
    - Runtime (Minutes)

---
config: prod_sent
tab_cols:
  - Product_Type
categorical_cols:
  - Product_Type
text_cols:
  - Product_Description
label_names:
  - "0"
  - "1"
  - "2"
  - "3"
label_col: Sentiment
num_labels: 4
prob_type: single_label_classification
wandb_proj_name: Product Sentiment
tnt_reorder_cols:
  bert:
    - Product_Type
    - Product_Description
  disbert:
    - Product_Type
    - Product_Description
  drob:
    - Product_Type
    - Product_Description
  deberta:
    - Product_Type
    - Product_Description
base_reorder_cols:
  bert:
    - Product_Type
    - Product_Description
  disbert:
    - Product_Type
    - Product_Description
  drob:
    - Product_Description
    - Product_Type
  deberta:
    - Product_Type
    - Product_Description

---
config: fake
tab_cols:
  - required_experience
  - required_education
categorical_cols:
  - required_experience
  - required_education
text_cols:
  - title
  - description
  - salary_range
label_names:
  - "0"
  - "1"
label_col: fraudulent
num_labels: 2
prob_type: single_label_classification
wandb_proj_name: Fake Job Postings
tnt_reorder_cols:
  bert:
    - description
    - title
    - required_experience
    - required_education
    - salary_range
  disbert:
    - description
    - title
    - required_education
    - required_experience
    - salary_range
  drob:
    - description
    - title
    - required_education
    - required_experience
    - salary_range
  deberta:
    - description
    - title
    - required_education
    - required_experience
    - salary_range
base_reorder_cols:
  bert:
    - description
    - title
    - required_education
    - required_experience
    - salary_range
  disbert:
    - description
    - title
    - required_education
    - required_experience
    - salary_range
  drob:
    - description
    - title
    - required_experience
    - required_education
    - salary_range
  deberta:
    - description
    - title
    - required_education
    - salary_range
    - required_experience
