--- # airbnb_0
config: airbnb_0
tags:
- bert
dataset: airbnb
batch_size: 32

--- # books_0
config: books_0
tags:
- bert
batch_size: 32
early_stopping_patience: 5

--- # imdb_0
config: imdb_0
tags:
- bert
batch_size: 32
dataset: imdb
early_stopping_patience: 5

--- # imdb_genre_0
config: imdb_genre_0
model_base: distilbert-base-uncased
tags:
- distilbert
dataset: imdb_genre
batch_size: 64

--- # imdb_genre_text_0
config: imdb_genre_text_0
model_base: distilbert-base-uncased
tags:
- distilbert
dataset: imdb_genre_text
batch_size: 32

--- # TESTING
config: testing
fast_dev_run: true
do_train: true
model_base: distilbert-base-uncased
tags:
- distilbert
dataset: imdb_genre
batch_size: 16