--- # airbnb_0
config: airbnb_0
fast_dev_run: false
tags:
- bert
dataset: airbnb
batch_size: 8

--- # books_0
config: books_0
fast_dev_run: false
tags:
- bert
batch_size: 16

--- # TESTING
config: testing
do_train: false
tags:
- bert
dataset: books