--- # imdb_genre_0
config: imdb_genre_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: imdb_genre
version: all_as_text
batch_size: 32

--- # imdb_genre_1
config: imdb_genre_1
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_base_reorder
dataset: imdb_genre
version: all_as_text_base_reorder
batch_size: 32

--- # imdb_genre_2
config: imdb_genre_2
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_tnt_reorder
dataset: imdb_genre
version: all_as_text_tnt_reorder
batch_size: 32

--- # imdb_genre_9
config: imdb_genre_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: imdb_genre
version: text_col_only
batch_size: 32

--- # prod_sent_0
config: prod_sent_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: prod_sent
version: all_as_text
batch_size: 128

# --- # prod_sent_1
# config: prod_sent_1
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - all_as_text_base_reorder
# dataset: prod_sent
# version: all_as_text_base_reorder
# batch_size: 128

# --- # prod_sent_2
# config: prod_sent_2
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - all_as_text_tnt_reorder
# dataset: prod_sent
# version: all_as_text_tnt_reorder
# batch_size: 128

--- # prod_sent_9
config: prod_sent_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: prod_sent
version: text_col_only
batch_size: 32

--- # fake_0
config: fake_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: fake
version: all_as_text
batch_size: 128

# --- # fake_1
# config: fake_1
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - all_as_text_base_reorder
# dataset: fake
# version: all_as_text_base_reorder
# batch_size: 128

--- # fake_2
config: fake_2
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_tnt_reorder
dataset: fake
version: all_as_text_tnt_reorder
batch_size: 128

--- # fake_9
config: fake_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: fake
version: text_col_only
batch_size: 32

--- # kick_0
config: kick_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: kick
version: all_as_text
batch_size: 128

--- # kick_1
config: kick_1
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_base_reorder
dataset: kick
version: all_as_text_base_reorder
batch_size: 128

--- # kick_2
config: kick_2
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_tnt_reorder
dataset: kick
version: all_as_text_tnt_reorder
batch_size: 128

--- # kick_9
config: kick_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: kick
version: text_col_only
batch_size: 32

--- # jigsaw_0
config: jigsaw_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: jigsaw
version: all_as_text
batch_size: 128

--- # jigsaw_1
config: jigsaw_1
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_base_reorder
dataset: jigsaw
version: all_as_text_base_reorder
batch_size: 128

--- # jigsaw_2
config: jigsaw_2
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_tnt_reorder
dataset: jigsaw
version: all_as_text_tnt_reorder
batch_size: 128

--- # jigsaw_9
config: jigsaw_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: jigsaw
version: text_col_only
batch_size: 32

--- # wine_0
config: wine_0
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: wine
version: all_as_text
batch_size: 32

# --- # wine_1
# config: wine_1
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - all_as_text_base_reorder
# dataset: wine
# version: all_as_text_base_reorder
# batch_size: 32

--- # wine_2
config: wine_2
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text_tnt_reorder
dataset: wine
version: all_as_text_tnt_reorder
batch_size: 32

--- # wine_9
config: wine_9
model_base: distilbert-base-uncased
tags:
  - distilbert
  - text_col_only
dataset: wine
version: text_col_only
batch_size: 32

--- # imdb_genre_10
config: imdb_genre_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: imdb_genre
version: all_as_text
batch_size: 32

--- # imdb_genre_19
config: imdb_genre_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: imdb_genre
version: text_col_only
batch_size: 32

--- # prod_sent_10
config: prod_sent_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: prod_sent
version: all_as_text
batch_size: 32

--- # prod_sent_19
config: prod_sent_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: prod_sent
version: text_col_only
batch_size: 32

--- # fake_10
config: fake_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: fake
version: all_as_text
batch_size: 32

--- # fake_19
config: fake_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: fake
version: text_col_only
batch_size: 32

--- # kick_10
config: kick_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: kick
version: all_as_text
batch_size: 32

--- # kick_19
config: kick_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: kick
version: text_col_only
batch_size: 32

--- # jigsaw_10
config: jigsaw_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: jigsaw
version: all_as_text
batch_size: 32

--- # jigsaw_19
config: jigsaw_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: jigsaw
version: text_col_only
batch_size: 32

--- # wine_10
config: wine_10
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - all_as_text
dataset: wine
version: all_as_text
batch_size: 32

--- # wine_19
config: wine_19
model_base: bert-base-uncased
tags:
  - bert-base-uncased
  - text_col_only
dataset: wine
version: text_col_only
batch_size: 32

# Old
##########################################
# --- # airbnb_0
# config: airbnb_0
# tags:
#   - bert
# dataset: airbnb
# batch_size: 32

# --- # books_0
# config: books_0
# tags:
#   - bert
# batch_size: 32
# early_stopping_patience: 5

# --- # imdb_0
# config: imdb_0
# tags:
#   - bert
# batch_size: 32
# dataset: imdb
# early_stopping_patience: 5

# --- # imdb_genre_1
# config: imdb_genre_1
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - tab_as_text
# dataset: imdb_genre
# version: tab_as_text
# batch_size: 32

# --- # imdb_genre_2
# config: imdb_genre_2
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - tabx5
# dataset: imdb_genre
# version: tabx5
# batch_size: 32

# --- # imdb_genre_3
# config: imdb_genre_3
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - reorder1
# dataset: imdb_genre
# version: reorder1
# batch_size: 32

# --- # imdb_genre_4
# config: imdb_genre_4
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - reorder2
# dataset: imdb_genre
# version: reorder2
# batch_size: 32

# --- # imdb_genre_5
# config: imdb_genre_5
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - tabx5_nodesc
# dataset: imdb_genre
# version: tabx5_nodesc
# batch_size: 32

# --- # imdb_genre_6
# config: imdb_genre_6
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - tabx2_nodesc
# dataset: imdb_genre
# version: tabx2_nodesc
# batch_size: 32

# --- # imdb_genre_7
# config: imdb_genre_7
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - tabx2
# dataset: imdb_genre
# version: tabx2
# batch_size: 32

# --- # imdb_genre_8
# config: imdb_genre_8
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - reorder3
# dataset: imdb_genre
# version: reorder3
# batch_size: 32

# --- # imdb_genre_10
# config: imdb_genre_10
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
#   - all_as_text_exp_reorder
# dataset: imdb_genre
# version: all_as_text_exp_reorder
# batch_size: 32

# --- # imdb_genre_text_0
# config: imdb_genre_text_0
# model_base: distilbert-base-uncased
# tags:
#   - distilbert
# dataset: imdb_genre_text
# batch_size: 32

--- # TESTING
config: testing
fast_dev_run: true
do_train: true
model_base: distilbert-base-uncased
tags:
  - distilbert
  - all_as_text
dataset: wine
version: all_as_text
batch_size: 32
